server:
  port: 8088
  servlet:
    context-path: /metadata

spring:
  datasource:
    name: mysql_metadata
    type: com.alibaba.druid.pool.DruidDataSource
    # druid相关配置
    druid:
      # 监控统计拦截的filters
      filters: stat
      driver-class-name: com.mysql.cj.jdbc.Driver
      # 基本属性
      url: jdbc:mysql://10.0.0.85:3306/metadata2?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: root
      password: admin
      # 配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 21
      # 获取连接等待超时时间
      max-wait: 60000
      # 间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      # 一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
  profiles:
    active: dubbo,config
  mvc:
    throw-exception-if-no-handler-found: true
  pid:
    file: src/main/resources/application.pid

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ys.idatrix.metacube.domain

# pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check

# logback 配置
logging:
  config: classpath:logback-spring.xml
  level:
    com.ys.idatrix.metacube.metamanage.mapper: debug
    com.ys.idatrix.metacube.dubbo.provider: debug
    io.swagger.models.parameters.AbstractSerializableParameter: error

management:
  endpoints:
    web:
      exposure:
        include: "*"  # * 在yaml 文件属于关键字，所以需要加引号

